"""Coordinator Agent — decompose, orchestrate fan-out + debate, synthesise.

  decompose(profile)                  -> dict[str, str]   (6 sub_tasks)
  synthesise(outputs, critic, profile)-> FinalPlan
  run(profile, ...)                   -> FinalPlan         (full pipeline)

The pipeline emits TraceEvents at every step so the live Agent Trace View can
follow along. Both decompose and synthesise have deterministic fallbacks, so the
whole system runs end-to-end without an API key (degraded but coherent).
"""

from __future__ import annotations

import asyncio
import os
import time
import uuid

from features.agents.base import AgentError, SessionContext, call_claude, extract_json
from features.coordinator.prompts import (
    COORDINATOR_DECOMPOSE_SYSTEM,
    SYNTHESIS_SYSTEM_PROMPT,
)
from features.debate.critique_loop import AGENT_RUNNERS, run_debate
from features.trace.logger import Tracer
from schemas.agent_schemas import (
    AgentOutput,
    FinalPlan,
    TraceEventType,
    UserProfile,
)

SPECIALISTS = ("nutrition", "macros", "fitness", "risk", "budget")

DISCLAIMER = (
    "This plan is generated by an AI system for educational purposes only and is "
    "not a substitute for professional medical advice, diagnosis, or treatment. "
    "Consult a qualified healthcare provider before starting any diet or exercise "
    "programme, especially if you have a medical condition."
)

_RISK_PENALTY = {"low": 0.0, "medium": 1.5, "high": 3.5, "critical": 6.0}


# ---------------------------------------------------------------------------
# Decompose
# ---------------------------------------------------------------------------


def _fallback_subtasks(profile: UserProfile) -> dict[str, str]:
    """Deterministic decomposition when the LLM is unavailable."""
    p = profile
    base = (
        f"age {p.age}, {p.sex.value}, {p.weight_kg:g} kg, {p.height_cm:g} cm, "
        f"{p.activity_level.value}, goal {p.primary_goal.value}, "
        f"medical {p.medical_conditions or ['none']}, "
        f"diet {p.dietary_restrictions or ['none']}, "
        f"budget INR {p.weekly_budget_inr:g}/week, gym access {p.gym_access}"
    )
    return {
        "nutrition": f"You are the Nutrition Agent. User: {base}. Design a 5-meal daily diet plan.",
        "macros": f"You are the Macros Agent. User: {base}. Compute precise macro/micro targets.",
        "fitness": f"You are the Fitness Agent. User: {base}. Design a 7-day workout programme.",
        "risk": f"You are the Risk Agent. User: {base}. Review for contraindications and red flags.",
        "budget": f"You are the Budget Agent. User: {base}. Cost the plan against the weekly budget.",
        "critic": (
            "You are the Critic Agent. Review nutrition, macros, fitness, risk, and budget "
            "outputs for consistency, safety, and budget feasibility."
        ),
    }


async def decompose(profile: UserProfile) -> dict[str, str]:
    """Break the profile into 6 self-contained sub_tasks (one per agent)."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return _fallback_subtasks(profile)
    try:
        raw = await call_claude(
            COORDINATOR_DECOMPOSE_SYSTEM,
            profile.model_dump_json(),
            temperature=0.3,
            max_tokens=2048,
            prefill="{",
        )
        parsed = extract_json(raw)
        required = {"nutrition", "macros", "fitness", "risk", "budget", "critic"}
        if not required.issubset(parsed) or not all(
            isinstance(parsed[k], str) and parsed[k].strip() for k in required
        ):
            return _fallback_subtasks(profile)
        return {k: parsed[k] for k in required}
    except AgentError:
        return _fallback_subtasks(profile)


# ---------------------------------------------------------------------------
# Synthesise
# ---------------------------------------------------------------------------


def _health_score(
    by_name: dict[str, AgentOutput], consistency: float, final_safe: bool
) -> float:
    score = 10.0
    risk = by_name.get("risk")
    if risk:
        level = str(risk.data.get("overall_risk_level", "low"))
        score -= _RISK_PENALTY.get(level, 0.0)
    budget = by_name.get("budget")
    if budget and budget.data.get("within_budget") is False:
        score -= 1.0
    score -= (1.0 - consistency) * 2.0
    if not final_safe:
        score -= 2.0
    return round(max(0.0, min(10.0, score)), 1)


def _fallback_narrative(
    profile: UserProfile, by_name: dict[str, AgentOutput], final_safe: bool
) -> tuple[str, list[str], list[str]]:
    goal = profile.primary_goal.value.replace("_", " ")
    macros = by_name.get("macros")
    target = macros.data.get("target_calories") if macros else None
    risk = by_name.get("risk")
    level = str(risk.data.get("overall_risk_level", "low")) if risk else "low"
    budget = by_name.get("budget")
    within = budget.data.get("within_budget", True) if budget else True

    user_summary = (
        f"Here is your personalised {goal} plan. It balances nutrition, training, "
        f"medical safety, and your weekly budget."
        + ("" if final_safe else " Please obtain physician clearance before starting.")
    )
    insights = [
        ("Physician clearance is recommended before you begin."
         if not final_safe else f"Your overall medical risk is assessed as {level}."),
        f"Daily calorie target is {int(target)} kcal." if target else
        "Calorie targets are aligned across your nutrition and macros plans.",
        "Your training week mixes cardio and strength to match your goal.",
        ("Your plan fits within your weekly budget." if within
         else "Your plan is slightly over budget — see the suggested swaps."),
        "Consistency over four weeks matters more than intensity in any single session.",
    ]
    actions = [
        "Day 1: Log your meals and take a 20-minute brisk walk.",
        "Day 2: Complete the first strength session; hydrate well.",
        "Day 3: Active recovery — light stretching and a short walk.",
        "Day 4: Cardio session; prep meals for the next two days.",
        "Day 5: Strength session; review your calorie log.",
        "Day 6: Longer cardio or a fun activity you enjoy.",
        "Day 7: Rest, reflect on the week, and plan next week's groceries.",
    ]
    return user_summary, insights, actions


async def _llm_narrative(
    profile: UserProfile,
    by_name: dict[str, AgentOutput],
    critic: AgentOutput,
) -> tuple[str, list[str], list[str]] | None:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    try:
        payload = {
            "profile": profile.model_dump(),
            "agent_outputs": {n: o.data for n, o in by_name.items()},
            "qa_review": critic.data,
        }
        raw = await call_claude(
            SYNTHESIS_SYSTEM_PROMPT,
            f"Synthesise a plan from:\n{payload}",
            temperature=0.5,
            max_tokens=1500,
            prefill="{",
        )
        parsed = extract_json(raw)
        summary = str(parsed.get("user_summary", "")).strip()
        insights = [str(x).strip() for x in parsed.get("key_insights", []) if str(x).strip()]
        actions = [str(x).strip() for x in parsed.get("action_steps_week_1", []) if str(x).strip()]
        if not summary or len(insights) < 5 or len(actions) < 7:
            return None
        return summary, insights[:5], actions[:7]
    except AgentError:
        return None


async def synthesise(
    agent_outputs: list[AgentOutput],
    critic_output: AgentOutput,
    profile: UserProfile,
    *,
    plan_id: str | None = None,
    debate_rounds: int = 1,
) -> FinalPlan:
    """Assemble the FinalPlan from specialist outputs + the critic's QA."""
    by_name = {o.agent_name: o for o in agent_outputs}
    consistency = float(critic_output.data.get("consistency_score", 1.0))
    final_safe = bool(critic_output.data.get("final_recommendation_safe", True))

    narrative = await _llm_narrative(profile, by_name, critic_output)
    if narrative is None:
        narrative = _fallback_narrative(profile, by_name, final_safe)
    user_summary, key_insights, action_steps = narrative

    def data_of(name: str) -> dict:
        out = by_name.get(name)
        return dict(out.data) if out else {}

    return FinalPlan(
        plan_id=plan_id or uuid.uuid4().hex,
        user_summary=user_summary,
        overall_health_score=_health_score(by_name, consistency, final_safe),
        nutrition_plan=data_of("nutrition"),
        macros_targets=data_of("macros"),
        fitness_programme=data_of("fitness"),
        risk_assessment=data_of("risk"),
        budget_analysis=data_of("budget"),
        key_insights=key_insights,
        action_steps_week_1=action_steps,
        disclaimer=DISCLAIMER,
        debate_rounds=debate_rounds,
        consistency_score=consistency,
        final_recommendation_safe=final_safe,
    )


# ---------------------------------------------------------------------------
# Full pipeline
# ---------------------------------------------------------------------------


async def run(
    profile: UserProfile,
    max_debate_rounds: int = 3,
    run_id: str | None = None,
) -> FinalPlan:
    """decompose -> fan-out (5 agents) -> debate -> synthesise. Emits trace."""
    run_id = run_id or uuid.uuid4().hex
    tracer = Tracer(run_id)
    session = SessionContext(plan_id=run_id)
    await tracer.emit(TraceEventType.RUN_STARTED, message="Run started")

    try:
        sub_tasks = await decompose(profile)
        await tracer.emit(
            TraceEventType.AGENT_COMPLETED,
            agent_name="coordinator",
            message="Decomposed profile into sub-tasks",
        )

        # Fan out the five specialists in parallel (timed per agent).
        for name in SPECIALISTS:
            await tracer.emit(TraceEventType.AGENT_STARTED, agent_name=name, round=1)

        async def _run_timed(agent: str) -> tuple[AgentOutput, float]:
            t0 = time.perf_counter()
            out = await AGENT_RUNNERS[agent](
                sub_tasks[agent], profile, round=1, session_context=session
            )
            return out, (time.perf_counter() - t0) * 1000.0

        results = await asyncio.gather(
            *(_run_timed(name) for name in SPECIALISTS), return_exceptions=True
        )

        outputs: list[AgentOutput] = []
        for name, res in zip(SPECIALISTS, results):
            if isinstance(res, tuple):
                out, duration_ms = res
                outputs.append(out)
                await tracer.emit(
                    TraceEventType.AGENT_COMPLETED,
                    agent_name=name,
                    round=1,
                    message=out.verdict,
                    payload={"confidence": out.confidence, "flags": out.flags},
                    duration_ms=duration_ms,
                )
            else:
                await tracer.emit(
                    TraceEventType.ERROR,
                    agent_name=name,
                    message=f"{type(res).__name__}: {res}",
                )

        # Debate loop (critic + targeted re-runs).
        debate = await run_debate(
            outputs,
            profile,
            sub_tasks,
            max_rounds=max_debate_rounds,
            tracer=tracer,
            session_context=session,
        )

        # Synthesise the final plan.
        await tracer.emit(TraceEventType.SYNTHESIS, agent_name="coordinator")
        plan = await synthesise(
            debate.final_outputs,
            debate.critic,
            profile,
            plan_id=run_id,
            debate_rounds=debate.rounds,
        )

        # Persist the finished plan so GET /api/plans/{plan_id} can serve it.
        await tracer.save_result(plan)

        await tracer.emit(
            TraceEventType.RUN_COMPLETED,
            agent_name="coordinator",
            message="Plan ready",
            payload={
                "plan_id": plan.plan_id,
                "overall_health_score": plan.overall_health_score,
                "final_recommendation_safe": plan.final_recommendation_safe,
            },
        )
        return plan

    except Exception as exc:
        await tracer.emit(
            TraceEventType.ERROR, message=f"Pipeline failed: {type(exc).__name__}: {exc}"
        )
        raise
