"""Coordinator Agent — decompose, orchestrate fan-out + debate, synthesise.

  decompose(profile)                  -> dict[str, str]   (6 sub_tasks)
  synthesise(outputs, critic, profile)-> FinalPlan
  run(profile, ...)                   -> FinalPlan         (full pipeline)

The pipeline emits TraceEvents at every step so the live Agent Trace View can
follow along. The system hard-requires GEMINI_API_KEY: decompose and synthesise
call Gemini directly and fail fast (no offline fallback) when the model returns
nothing usable, surfacing the failure as an ERROR trace event.
"""

from __future__ import annotations

import asyncio
import time
import uuid

from features.agents.base import (
    AgentParseError,
    SessionContext,
    call_claude,
    extract_json,
)
from features.coordinator.prompts import (
    COORDINATOR_DECOMPOSE_SYSTEM,
    SYNTHESIS_SYSTEM_PROMPT,
)
from features.debate.critique_loop import AGENT_RUNNERS, run_debate
from features.trace.logger import Tracer
from schemas.agent_schemas import (
    AgentOutput,
    FinalPlan,
    TraceEventType,
    UserProfile,
)

DISCLAIMER = (
    "This plan is generated by an AI system for educational purposes only and is "
    "not a substitute for professional medical advice, diagnosis, or treatment. "
    "Consult a qualified healthcare provider before starting any diet or exercise "
    "programme, especially if you have a medical condition."
)

_RISK_PENALTY = {"low": 0.0, "medium": 1.5, "high": 3.5, "critical": 6.0}

# ---------------------------------------------------------------------------
# Agent-to-agent communication
#
# Specialists no longer run as one blind parallel wave. They run as a dependency
# pipeline: each agent receives the structured outputs of the agents it depends
# on (threaded in as `peer_context`), so conclusions flow downstream — Macros'
# targets shape Nutrition's meals, Nutrition + Fitness costs feed Budget, and
# Risk screens everything. After the draft, a cross-examination round lets every
# agent validate or challenge its peers' conclusions and revise to reconcile.
# ---------------------------------------------------------------------------

# agent -> the upstream agents whose structured output it consumes.
DEPENDENCIES: dict[str, tuple[str, ...]] = {
    "macros": (),  # pure Mifflin–St Jeor computation from the profile
    "fitness": (),  # training programme from goal / activity / gym access
    "nutrition": ("macros", "fitness"),  # meals must hit macro targets & fuel training
    "budget": ("nutrition", "fitness"),  # price the actual foods + gym/supplements
    "risk": ("macros", "fitness", "nutrition", "budget"),  # screens every draft
}

# Topological layering of DEPENDENCIES. Agents within a stage run in parallel;
# stages run in order so dependents see their upstreams' outputs.
PIPELINE_STAGES: tuple[tuple[str, ...], ...] = (
    ("macros", "fitness"),
    ("nutrition",),
    ("budget",),
    ("risk",),
)

CROSS_EXAM_DIRECTIVE = (
    "\n\nCROSS-EXAMINATION ROUND. Your peers' structured conclusions are provided "
    "as peer context above. For every peer conclusion that touches your domain, "
    "decide whether you VALIDATE it (consistent and sound) or CHALLENGE it (state "
    "the specific conflict and the concrete change you would request). Then REVISE "
    "your own output so it is fully consistent with the conclusions you validated. "
    "Keep your JSON response schema EXACTLY the same; record each validation or "
    "challenge as a short string in the 'flags' array, prefixed with 'validate:' "
    "or 'challenge:' and naming the peer (e.g. 'challenge:budget — ...')."
)


async def _run_agent_timed(
    name: str,
    sub_task: str,
    profile: UserProfile,
    *,
    peer_context: dict | None,
    round: int,
    session: SessionContext,
) -> tuple[AgentOutput, float]:
    """Run one specialist, returning its output and wall-clock duration (ms)."""
    t0 = time.perf_counter()
    out = await AGENT_RUNNERS[name](
        sub_task,
        profile,
        peer_context=peer_context or None,
        round=round,
        session_context=session,
    )
    return out, (time.perf_counter() - t0) * 1000.0


def _completed_payload(out: AgentOutput, **extra: object) -> dict:
    """Rich AGENT_COMPLETED payload consumed by the Step-Detail drawer."""
    payload = {
        "verdict": out.verdict,
        "reasoning": out.reasoning,
        "output": out.data,
        "sources": out.data.get("sources", []),
        "confidence": out.confidence,
        "flags": out.flags,
    }
    payload.update(extra)
    return payload


async def _run_pipeline(
    sub_tasks: dict[str, str],
    profile: UserProfile,
    session: SessionContext,
    tracer: Tracer,
) -> dict[str, AgentOutput]:
    """Run the specialists as a dependency pipeline (round 1 drafts).

    Each agent receives its upstream dependencies' structured outputs as
    peer_context; the emitted trace edges (peer_context_agents) are the real
    dependency edges the graph renders."""
    outputs: dict[str, AgentOutput] = {}

    for stage in PIPELINE_STAGES:
        for name in stage:
            deps = DEPENDENCIES[name]
            await tracer.emit(
                TraceEventType.AGENT_STARTED,
                agent_name=name,
                round=1,
                payload={
                    "input": sub_tasks[name],
                    "peer_context_agents": list(deps),
                    "round": 1,
                },
            )

        async def _one(name: str) -> tuple[str, AgentOutput | None, float, Exception | None]:
            deps = DEPENDENCIES[name]
            peer_context = {d: outputs[d].data for d in deps if d in outputs}
            try:
                out, dur = await _run_agent_timed(
                    name, sub_tasks[name], profile,
                    peer_context=peer_context, round=1, session=session,
                )
                return name, out, dur, None
            except Exception as exc:  # noqa: BLE001 — isolate one agent's failure
                return name, None, 0.0, exc

        for name, out, dur, exc in await asyncio.gather(*(_one(n) for n in stage)):
            if exc is not None or out is None:
                await tracer.emit(
                    TraceEventType.ERROR,
                    agent_name=name,
                    message=f"{type(exc).__name__}: {exc}",
                )
                continue
            outputs[name] = out
            await tracer.emit(
                TraceEventType.AGENT_COMPLETED,
                agent_name=name,
                round=1,
                message=out.verdict,
                payload=_completed_payload(out, peer_context_agents=list(DEPENDENCIES[name])),
                duration_ms=dur,
            )

    session.record_outputs(1, outputs)
    return outputs


async def _cross_examine(
    sub_tasks: dict[str, str],
    profile: UserProfile,
    drafts: dict[str, AgentOutput],
    session: SessionContext,
    tracer: Tracer,
) -> dict[str, AgentOutput]:
    """Round 2: every agent validates or challenges its peers and refines.

    Each agent re-runs with the *full* set of peer outputs and the
    cross-examination directive; the refined outputs feed the Critic debate."""
    names = [n for n in DEPENDENCIES if n in drafts]
    if len(names) < 2:
        return drafts  # nothing to cross-examine against

    for name in names:
        peers = [n for n in names if n != name]
        await tracer.emit(
            TraceEventType.AGENT_STARTED,
            agent_name=name,
            round=2,
            message="Cross-examining peers",
            payload={
                "input": sub_tasks[name] + CROSS_EXAM_DIRECTIVE,
                "peer_context_agents": peers,
                "round": 2,
            },
        )

    async def _one(name: str) -> tuple[str, AgentOutput | None, float, Exception | None]:
        peers = {n: drafts[n].data for n in names if n != name}
        try:
            out, dur = await _run_agent_timed(
                name, sub_tasks[name] + CROSS_EXAM_DIRECTIVE, profile,
                peer_context=peers, round=2, session=session,
            )
            return name, out, dur, None
        except Exception as exc:  # noqa: BLE001 — keep the draft on failure
            return name, None, 0.0, exc

    refined: dict[str, AgentOutput] = dict(drafts)
    for name, out, dur, exc in await asyncio.gather(*(_one(n) for n in names)):
        if exc is not None or out is None:
            continue  # keep the round-1 draft for this agent
        refined[name] = out
        challenges = [f for f in out.flags if f.lower().startswith(("challenge", "validate"))]
        await tracer.emit(
            TraceEventType.AGENT_COMPLETED,
            agent_name=name,
            round=2,
            message=out.verdict,
            payload=_completed_payload(
                out,
                revised=True,
                phase="cross_examination",
                peer_context_agents=[n for n in names if n != name],
                challenges=challenges,
            ),
            duration_ms=dur,
        )

    session.record_outputs(2, refined)
    return refined


# ---------------------------------------------------------------------------
# Decompose
# ---------------------------------------------------------------------------


async def decompose(
    profile: UserProfile, directives: str | None = None
) -> dict[str, str]:
    """Break the profile into 6 self-contained sub_tasks (one per agent).

    `directives` is an optional free-form change request (from a re-plan turn,
    e.g. "make it cheaper") that is woven into every sub-task so the whole
    pipeline honours it. Fails fast (raises) if Gemini is unavailable or returns
    an incomplete set of sub-tasks — there is no offline decomposition.
    """
    user_content = profile.model_dump_json()
    if directives:
        user_content += (
            "\n\nADDITIONAL USER DIRECTIVE FOR THIS REVISION (apply across ALL "
            f"sub-tasks): {directives}"
        )
    raw = await call_claude(
        COORDINATOR_DECOMPOSE_SYSTEM,
        user_content,
        temperature=0.3,
        max_tokens=2048,
        prefill="{",
    )
    parsed = extract_json(raw)
    required = {"nutrition", "macros", "fitness", "risk", "budget", "critic"}
    if not required.issubset(parsed) or not all(
        isinstance(parsed.get(k), str) and parsed[k].strip() for k in required
    ):
        raise AgentParseError(
            "Coordinator decompose returned incomplete sub-tasks; missing/blank: "
            f"{sorted(k for k in required if not str(parsed.get(k, '')).strip())}"
        )
    return {k: parsed[k] for k in required}


# ---------------------------------------------------------------------------
# Synthesise
# ---------------------------------------------------------------------------


def _health_score(
    by_name: dict[str, AgentOutput], consistency: float, final_safe: bool
) -> float:
    score = 10.0
    risk = by_name.get("risk")
    if risk:
        level = str(risk.data.get("overall_risk_level", "low"))
        score -= _RISK_PENALTY.get(level, 0.0)
    budget = by_name.get("budget")
    if budget and budget.data.get("within_budget") is False:
        score -= 1.0
    score -= (1.0 - consistency) * 2.0
    if not final_safe:
        score -= 2.0
    return round(max(0.0, min(10.0, score)), 1)


async def _llm_narrative(
    profile: UserProfile,
    by_name: dict[str, AgentOutput],
    critic: AgentOutput,
) -> tuple[str, list[str], list[str]]:
    """Generate the synthesis narrative via Gemini.

    Raises AgentParseError on an incomplete narrative — there is no offline
    fallback, so a failure here surfaces as a pipeline ERROR rather than canned
    prose.
    """
    payload = {
        "profile": profile.model_dump(),
        "agent_outputs": {n: o.data for n, o in by_name.items()},
        "qa_review": critic.data,
    }
    raw = await call_claude(
        SYNTHESIS_SYSTEM_PROMPT,
        f"Synthesise a plan from:\n{payload}",
        temperature=0.5,
        max_tokens=1500,
        prefill="{",
    )
    parsed = extract_json(raw)
    summary = str(parsed.get("user_summary", "")).strip()
    insights = [str(x).strip() for x in parsed.get("key_insights", []) if str(x).strip()]
    actions = [str(x).strip() for x in parsed.get("action_steps_week_1", []) if str(x).strip()]
    if not summary or len(insights) < 5 or len(actions) < 7:
        raise AgentParseError(
            "Synthesis narrative incomplete "
            f"(summary={bool(summary)}, insights={len(insights)}, actions={len(actions)})"
        )
    return summary, insights[:5], actions[:7]


async def synthesise(
    agent_outputs: list[AgentOutput],
    critic_output: AgentOutput,
    profile: UserProfile,
    *,
    plan_id: str | None = None,
    debate_rounds: int = 1,
) -> FinalPlan:
    """Assemble the FinalPlan from specialist outputs + the critic's QA."""
    by_name = {o.agent_name: o for o in agent_outputs}
    consistency = float(critic_output.data.get("consistency_score", 1.0))
    final_safe = bool(critic_output.data.get("final_recommendation_safe", True))

    user_summary, key_insights, action_steps = await _llm_narrative(
        profile, by_name, critic_output
    )

    def data_of(name: str) -> dict:
        out = by_name.get(name)
        return dict(out.data) if out else {}

    return FinalPlan(
        plan_id=plan_id or uuid.uuid4().hex,
        user_summary=user_summary,
        overall_health_score=_health_score(by_name, consistency, final_safe),
        nutrition_plan=data_of("nutrition"),
        macros_targets=data_of("macros"),
        fitness_programme=data_of("fitness"),
        risk_assessment=data_of("risk"),
        budget_analysis=data_of("budget"),
        key_insights=key_insights,
        action_steps_week_1=action_steps,
        disclaimer=DISCLAIMER,
        debate_rounds=debate_rounds,
        consistency_score=consistency,
        final_recommendation_safe=final_safe,
    )


# ---------------------------------------------------------------------------
# Full pipeline
# ---------------------------------------------------------------------------


async def run(
    profile: UserProfile,
    max_debate_rounds: int = 3,
    run_id: str | None = None,
    directives: str | None = None,
) -> FinalPlan:
    """decompose -> fan-out (5 agents) -> debate -> synthesise. Emits trace.

    `directives` carries an optional re-plan change request through decomposition.
    """
    run_id = run_id or uuid.uuid4().hex
    tracer = Tracer(run_id)
    session = SessionContext(plan_id=run_id)
    await tracer.emit(TraceEventType.RUN_STARTED, message="Run started")

    try:
        sub_tasks = await decompose(profile, directives)
        await tracer.emit(
            TraceEventType.AGENT_COMPLETED,
            agent_name="coordinator",
            message="Decomposed profile into sub-tasks",
            # The inputs the Coordinator routed to each agent — the graph reads
            # this to label Coordinator -> specialist edges and the step detail.
            payload={"sub_tasks": sub_tasks},
        )

        # Dependency pipeline (round 1 drafts): specialists run in topological
        # stages, each consuming its upstreams' structured outputs as peer
        # context, so conclusions flow Macros/Fitness -> Nutrition -> Budget,
        # with Risk screening every draft.
        drafts = await _run_pipeline(sub_tasks, profile, session, tracer)

        # Cross-examination (round 2): every agent validates or challenges its
        # peers' conclusions and revises to reconcile.
        refined = await _cross_examine(sub_tasks, profile, drafts, session, tracer)
        outputs = list(refined.values())

        # Debate loop (Critic QA + targeted re-runs) over the reconciled outputs.
        debate = await run_debate(
            outputs,
            profile,
            sub_tasks,
            max_rounds=max_debate_rounds,
            tracer=tracer,
            session_context=session,
        )

        # Synthesise the final plan.
        await tracer.emit(
            TraceEventType.SYNTHESIS,
            agent_name="coordinator",
            message="Synthesising final plan",
            # Which agents' outputs feed the synthesis — drives all -> Synthesis edges.
            payload={"inputs_from": [o.agent_name for o in debate.final_outputs]},
        )
        plan = await synthesise(
            debate.final_outputs,
            debate.critic,
            profile,
            plan_id=run_id,
            debate_rounds=debate.rounds,
        )

        # Persist the finished plan so GET /api/plans/{plan_id} can serve it.
        await tracer.save_result(plan)

        await tracer.emit(
            TraceEventType.RUN_COMPLETED,
            agent_name="coordinator",
            message="Plan ready",
            payload={
                "plan_id": plan.plan_id,
                "overall_health_score": plan.overall_health_score,
                "final_recommendation_safe": plan.final_recommendation_safe,
            },
        )
        return plan

    except Exception as exc:
        await tracer.emit(
            TraceEventType.ERROR, message=f"Pipeline failed: {type(exc).__name__}: {exc}"
        )
        raise
