"""Coordinator Agent — decompose, orchestrate fan-out + debate, synthesise.

  decompose(profile)                  -> dict[str, str]   (6 sub_tasks)
  synthesise(outputs, critic, profile)-> FinalPlan
  run(profile, ...)                   -> FinalPlan         (full pipeline)

The pipeline emits TraceEvents at every step so the live Agent Trace View can
follow along. The system hard-requires GEMINI_API_KEY: decompose and synthesise
call Gemini directly and fail fast (no offline fallback) when the model returns
nothing usable, surfacing the failure as an ERROR trace event.
"""

from __future__ import annotations

import asyncio
import time
import uuid

from features.agents.base import (
    AgentParseError,
    SessionContext,
    call_claude,
    extract_json,
)
from features.coordinator.prompts import (
    COORDINATOR_DECOMPOSE_SYSTEM,
    SYNTHESIS_SYSTEM_PROMPT,
)
from features.debate.critique_loop import AGENT_RUNNERS, run_debate
from features.trace.logger import Tracer
from schemas.agent_schemas import (
    AgentOutput,
    FinalPlan,
    TraceEventType,
    UserProfile,
)

SPECIALISTS = ("nutrition", "macros", "fitness", "risk", "budget")

DISCLAIMER = (
    "This plan is generated by an AI system for educational purposes only and is "
    "not a substitute for professional medical advice, diagnosis, or treatment. "
    "Consult a qualified healthcare provider before starting any diet or exercise "
    "programme, especially if you have a medical condition."
)

_RISK_PENALTY = {"low": 0.0, "medium": 1.5, "high": 3.5, "critical": 6.0}


# ---------------------------------------------------------------------------
# Decompose
# ---------------------------------------------------------------------------


async def decompose(
    profile: UserProfile, directives: str | None = None
) -> dict[str, str]:
    """Break the profile into 6 self-contained sub_tasks (one per agent).

    `directives` is an optional free-form change request (from a re-plan turn,
    e.g. "make it cheaper") that is woven into every sub-task so the whole
    pipeline honours it. Fails fast (raises) if Gemini is unavailable or returns
    an incomplete set of sub-tasks — there is no offline decomposition.
    """
    user_content = profile.model_dump_json()
    if directives:
        user_content += (
            "\n\nADDITIONAL USER DIRECTIVE FOR THIS REVISION (apply across ALL "
            f"sub-tasks): {directives}"
        )
    raw = await call_claude(
        COORDINATOR_DECOMPOSE_SYSTEM,
        user_content,
        temperature=0.3,
        max_tokens=2048,
        prefill="{",
    )
    parsed = extract_json(raw)
    required = {"nutrition", "macros", "fitness", "risk", "budget", "critic"}
    if not required.issubset(parsed) or not all(
        isinstance(parsed.get(k), str) and parsed[k].strip() for k in required
    ):
        raise AgentParseError(
            "Coordinator decompose returned incomplete sub-tasks; missing/blank: "
            f"{sorted(k for k in required if not str(parsed.get(k, '')).strip())}"
        )
    return {k: parsed[k] for k in required}


# ---------------------------------------------------------------------------
# Synthesise
# ---------------------------------------------------------------------------


def _health_score(
    by_name: dict[str, AgentOutput], consistency: float, final_safe: bool
) -> float:
    score = 10.0
    risk = by_name.get("risk")
    if risk:
        level = str(risk.data.get("overall_risk_level", "low"))
        score -= _RISK_PENALTY.get(level, 0.0)
    budget = by_name.get("budget")
    if budget and budget.data.get("within_budget") is False:
        score -= 1.0
    score -= (1.0 - consistency) * 2.0
    if not final_safe:
        score -= 2.0
    return round(max(0.0, min(10.0, score)), 1)


async def _llm_narrative(
    profile: UserProfile,
    by_name: dict[str, AgentOutput],
    critic: AgentOutput,
) -> tuple[str, list[str], list[str]]:
    """Generate the synthesis narrative via Gemini.

    Raises AgentParseError on an incomplete narrative — there is no offline
    fallback, so a failure here surfaces as a pipeline ERROR rather than canned
    prose.
    """
    payload = {
        "profile": profile.model_dump(),
        "agent_outputs": {n: o.data for n, o in by_name.items()},
        "qa_review": critic.data,
    }
    raw = await call_claude(
        SYNTHESIS_SYSTEM_PROMPT,
        f"Synthesise a plan from:\n{payload}",
        temperature=0.5,
        max_tokens=1500,
        prefill="{",
    )
    parsed = extract_json(raw)
    summary = str(parsed.get("user_summary", "")).strip()
    insights = [str(x).strip() for x in parsed.get("key_insights", []) if str(x).strip()]
    actions = [str(x).strip() for x in parsed.get("action_steps_week_1", []) if str(x).strip()]
    if not summary or len(insights) < 5 or len(actions) < 7:
        raise AgentParseError(
            "Synthesis narrative incomplete "
            f"(summary={bool(summary)}, insights={len(insights)}, actions={len(actions)})"
        )
    return summary, insights[:5], actions[:7]


async def synthesise(
    agent_outputs: list[AgentOutput],
    critic_output: AgentOutput,
    profile: UserProfile,
    *,
    plan_id: str | None = None,
    debate_rounds: int = 1,
) -> FinalPlan:
    """Assemble the FinalPlan from specialist outputs + the critic's QA."""
    by_name = {o.agent_name: o for o in agent_outputs}
    consistency = float(critic_output.data.get("consistency_score", 1.0))
    final_safe = bool(critic_output.data.get("final_recommendation_safe", True))

    user_summary, key_insights, action_steps = await _llm_narrative(
        profile, by_name, critic_output
    )

    def data_of(name: str) -> dict:
        out = by_name.get(name)
        return dict(out.data) if out else {}

    return FinalPlan(
        plan_id=plan_id or uuid.uuid4().hex,
        user_summary=user_summary,
        overall_health_score=_health_score(by_name, consistency, final_safe),
        nutrition_plan=data_of("nutrition"),
        macros_targets=data_of("macros"),
        fitness_programme=data_of("fitness"),
        risk_assessment=data_of("risk"),
        budget_analysis=data_of("budget"),
        key_insights=key_insights,
        action_steps_week_1=action_steps,
        disclaimer=DISCLAIMER,
        debate_rounds=debate_rounds,
        consistency_score=consistency,
        final_recommendation_safe=final_safe,
    )


# ---------------------------------------------------------------------------
# Full pipeline
# ---------------------------------------------------------------------------


async def run(
    profile: UserProfile,
    max_debate_rounds: int = 3,
    run_id: str | None = None,
    directives: str | None = None,
) -> FinalPlan:
    """decompose -> fan-out (5 agents) -> debate -> synthesise. Emits trace.

    `directives` carries an optional re-plan change request through decomposition.
    """
    run_id = run_id or uuid.uuid4().hex
    tracer = Tracer(run_id)
    session = SessionContext(plan_id=run_id)
    await tracer.emit(TraceEventType.RUN_STARTED, message="Run started")

    try:
        sub_tasks = await decompose(profile, directives)
        await tracer.emit(
            TraceEventType.AGENT_COMPLETED,
            agent_name="coordinator",
            message="Decomposed profile into sub-tasks",
            # The inputs the Coordinator routed to each agent — the graph reads
            # this to label Coordinator -> specialist edges and the step detail.
            payload={"sub_tasks": sub_tasks},
        )

        # Fan out the five specialists in parallel (timed per agent).
        for name in SPECIALISTS:
            await tracer.emit(
                TraceEventType.AGENT_STARTED,
                agent_name=name,
                round=1,
                # Full input received by the agent; no peers at the initial fan-out.
                payload={"input": sub_tasks[name], "peer_context_agents": [], "round": 1},
            )

        async def _run_timed(agent: str) -> tuple[AgentOutput, float]:
            t0 = time.perf_counter()
            out = await AGENT_RUNNERS[agent](
                sub_tasks[agent], profile, round=1, session_context=session
            )
            return out, (time.perf_counter() - t0) * 1000.0

        results = await asyncio.gather(
            *(_run_timed(name) for name in SPECIALISTS), return_exceptions=True
        )

        outputs: list[AgentOutput] = []
        for name, res in zip(SPECIALISTS, results):
            if isinstance(res, tuple):
                out, duration_ms = res
                outputs.append(out)
                await tracer.emit(
                    TraceEventType.AGENT_COMPLETED,
                    agent_name=name,
                    round=1,
                    message=out.verdict,
                    # Full output for the step-detail drawer: structured data,
                    # reasoning, web sources, confidence, flags.
                    payload={
                        "verdict": out.verdict,
                        "reasoning": out.reasoning,
                        "output": out.data,
                        "sources": out.data.get("sources", []),
                        "confidence": out.confidence,
                        "flags": out.flags,
                    },
                    duration_ms=duration_ms,
                )
            else:
                await tracer.emit(
                    TraceEventType.ERROR,
                    agent_name=name,
                    message=f"{type(res).__name__}: {res}",
                )

        # Debate loop (critic + targeted re-runs).
        debate = await run_debate(
            outputs,
            profile,
            sub_tasks,
            max_rounds=max_debate_rounds,
            tracer=tracer,
            session_context=session,
        )

        # Synthesise the final plan.
        await tracer.emit(
            TraceEventType.SYNTHESIS,
            agent_name="coordinator",
            message="Synthesising final plan",
            # Which agents' outputs feed the synthesis — drives all -> Synthesis edges.
            payload={"inputs_from": [o.agent_name for o in debate.final_outputs]},
        )
        plan = await synthesise(
            debate.final_outputs,
            debate.critic,
            profile,
            plan_id=run_id,
            debate_rounds=debate.rounds,
        )

        # Persist the finished plan so GET /api/plans/{plan_id} can serve it.
        await tracer.save_result(plan)

        await tracer.emit(
            TraceEventType.RUN_COMPLETED,
            agent_name="coordinator",
            message="Plan ready",
            payload={
                "plan_id": plan.plan_id,
                "overall_health_score": plan.overall_health_score,
                "final_recommendation_safe": plan.final_recommendation_safe,
            },
        )
        return plan

    except Exception as exc:
        await tracer.emit(
            TraceEventType.ERROR, message=f"Pipeline failed: {type(exc).__name__}: {exc}"
        )
        raise
